// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgmfwOtZ4QkQXMcreHRz306BoRRhCUBGI',
    appId: '1:213160916664:web:1227ccca5e9de3ac7ce64d',
    messagingSenderId: '213160916664',
    projectId: 'skycast-aaac5',
    authDomain: 'skycast-aaac5.firebaseapp.com',
    storageBucket: 'skycast-aaac5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG1CiUFfoYK-qa7cHduCXrRzQWTzeGnIk',
    appId: '1:213160916664:android:d076779fd3e0d4fd7ce64d',
    messagingSenderId: '213160916664',
    projectId: 'skycast-aaac5',
    storageBucket: 'skycast-aaac5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAOxat0tie2pMNJydP2oe0V_YEmKh6D8',
    appId: '1:213160916664:ios:19eb0e7dc1369cdb7ce64d',
    messagingSenderId: '213160916664',
    projectId: 'skycast-aaac5',
    storageBucket: 'skycast-aaac5.firebasestorage.app',
    iosBundleId: 'com.example.skycast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAOxat0tie2pMNJydP2oe0V_YEmKh6D8',
    appId: '1:213160916664:ios:19eb0e7dc1369cdb7ce64d',
    messagingSenderId: '213160916664',
    projectId: 'skycast-aaac5',
    storageBucket: 'skycast-aaac5.firebasestorage.app',
    iosBundleId: 'com.example.skycast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgmfwOtZ4QkQXMcreHRz306BoRRhCUBGI',
    appId: '1:213160916664:web:4034f737c7be9ae17ce64d',
    messagingSenderId: '213160916664',
    projectId: 'skycast-aaac5',
    authDomain: 'skycast-aaac5.firebaseapp.com',
    storageBucket: 'skycast-aaac5.firebasestorage.app',
  );
}
